### ISSUE TITLE
Questions about translations

### ISSUE THREAD

**Issue by rugk** [rugk/erobot-language-de#1]
@bartatamas 
Could you tell me where exactly this string is used?

> category_batch: Batch

https://github.com/rugk/erobot-language-de/blob/master/strings_global.xml#L32

**Comment by rugk** [comment]
And does 'This function is not available from Android X.Y ' (e.g. [here](https://github.com/rugk/erobot-language-de/blob/master/strings_global.xml#L56)) mean it's not available with v X.Y and higher or just with version X.Y?

**Comment by bartatamas** [comment]
category_batch is used in Elixir 2 only, it is for grouping batch actions, for example:

--- batch ---
remove all
disable all
--- filter ---
by name
by size

**Comment by bartatamas** [comment]
'This function is not available from Android X.Y '  means it is not available for X.Y and newer versions. The function is removed or disabled.

**Comment by rugk** [comment]
Okay thanks, for the second thing I changed some strings to fit better.

**Comment by rugk** [comment]
Here some new things which 
- Where is _param_action_audio_force_use_usage_dock_ used and what should 'dock' mean in this context?
- Where is _param_action_audio_force_use_usage_media_ used and what should it mean? A drive or music/video etc.?
- What does the 'delta' mean in this strings?
  '_param_action_coordinate_dx_'
  '_param_action_coordinate_dy_'
- What should '_param_action_execute_robot_command_enable_execute_itself_' mean? That you can cause loops with commands if you enable it?
- And where is '_param_action_horizontal_fill_' and '_param_action_horizontal_offset_' used? What's filled or off-setted there?
- What kind of 'intend' is this? '_param_action_intent_'
- And does '_param_action_locale_' has something to do with a language selection or what else?

(all in strings_actions.xml)

**Comment by bartatamas** [comment]
> Where is param_action_audio_force_use_usage_dock used and what should 'dock' mean in this context?

https://github.com/android/platform_frameworks_base/blob/master/media/java/android/media/AudioSystem.java#L528

> Where is param_action_audio_force_use_usage_media used and what should it mean? A drive or music/video etc.?

Same as above. No documentation about it. What kind of audio should be forced to speaker/headphone. Or similar.

> What does the 'delta' mean in this strings? 'param_action_coordinate_dx' 'param_action_coordinate_dy'

If delta is on then you will receive only changes. For example if X changes from 1 to 3 and if you click on delta, then you will receive 2 (3 - 1) instead of 3 (new x value).

> What should 'param_action_execute_robot_command_enable_execute_itself' mean? That you can cause loops with commands if you enable it?

If you create a command with name A and you add an action to it to execute itself: Execute Robot command (name=A) then it will be a recursive call and can call problems. It is disabled by default but you can enable it.

> And where is 'param_action_horizontal_fill' and 'param_action_horizontal_offset' used? What's filled or off-setted there?

It is used by the "Toast action" which displays toast messages. You can set with these parameters to make the toast message as width as possible or you can set the horizontal X offset, where to display the message.

> What kind of 'intend' is this? 'param_action_intent'

Intent. An Android thing: http://developer.android.com/reference/android/content/Intent.html

> And does 'param_action_locale' has something to do with a language selection or what else?

Locale = Country + Language

**Comment by rugk** [comment]
> Where is param_action_audio_force_use_usage_media used and what should it mean? A drive or music/video etc.?
> 
> Same as above. No documentation about it. What kind of audio should be forced to speaker/headphone. Or similar.

So it's about music/video - okay. :smile: 

BTW I've also changed some other things based on your answers. So thanks again.

**Comment by rugk** [comment]
And again I have to reopen this. 

What are 'param_action_plugin_blurb' and 'param_action_plugin_bundle'? A kind of plugins? So are these proper names?
And what should 'param_action_priority_assert' mean?

Still all in strings_actions.xml.

**Comment by rugk** [comment]
And just to confirm: 'expression_shortcuts' in strings_expressions.xml are expressions which are variable? (Not e.g. something like expressions stored in a variable)

**Comment by rugk** [comment]
And can you please give an example of 'expression_type_operator_element_at_text'? What are the parameters %1$ and %2$ in this case?

**Comment by rugk** [comment]
And BTW in 'expression_type_operator_match_help' there it states as an example:

> \"(\d+).(\d+)\" in \"13.31\" ist [13, 21]

Shouldn't this be [13, 31] as the last number is an 31?

**Comment by bartatamas** [comment]
> 'param_action_plugin_blurb' and 'param_action_plugin_bundle'

Yes, these are Locale plugin parameters. Blurb is a short text describing what action is doing, bundle is the parameters of this action. 

http://www.twofortyfouram.com/developer

Find Blurb Extra and Bundle Extra in this link.

> And what should 'param_action_priority_assert' mean?

It is ASSERT priority level for logging:

http://developer.android.com/reference/android/util/Log.html#ASSERT

Assert means a condition which should never happen. Worse than Error level.

> And just to confirm: 'expression_shortcuts' in strings_expressions.xml are expressions which are variable? 

They are named expressions. I mean you can give an expression a name, for example:

isNight = hour of day > 21 and hour of day < 6

And you needn't enter these whole expression again and again, you can name it (isNight) and use this name as a variable. When you evaluate expression Variable isNight, then the referenced expression will be evaluated.

> expression_type_operator_element_at_text

First parameter is the collection, second parameter is the index. So

[0,1,2] element at 2 is 1

> Shouldn't this be [13, 31] as the last number is an 31?

Yes, it is a typo

**Comment by rugk** [comment]
Okay, thanks. String changed.

**Comment by rugk** [comment]
Okay another question: [In some places](https://github.com/rugk/erobot-language-de/search?utf8=%E2%9C%93&q=Accessibility) you mention a kind of accessibility. What do you mean exactly there?

**Comment by bartatamas** [comment]
It is about System settings / Accessibility screen. There you can
enable/disable accessibility services like E-Robot service. Some features
are available only if this service is enabled.

**Comment by rugk** [comment]
Okay thanks.

**Comment by rugk** [comment]
And what is he_desk and le_desk here? https://github.com/rugk/erobot-language-de/blob/master/strings_expressions.xml#L166

**Comment by rugk** [comment]
Or is it better not to translate this values at all as they are returned by this expression?

**Comment by bartatamas** [comment]
Yes, these kind of values must not be translated as they are returned by
the expression.

**Comment by rugk** [comment]
Okay.
