### ISSUE TITLE
Encoding special characters

### ISSUE THREAD

**Issue by rugk** [rugk/erobot-language-de#2]
@bartatamas
If I use some of these characters - do I need to encode them? (They are very common in German)
`ä, ö, ü, Ä, Ö, Ü, ß`

And if I need to encode them - how should I encode them? Like HTML characters?

**Comment by bartatamas** [comment]
No encoding is needed. Xml should be UTF-8 encoded and you can write these characters in UTF-8 I guess.

**Comment by rugk** [comment]
Okay thanks, so I leave them as they are.
I just wondered because you sometimes encoded & as &amp; but if I don't need to encode them that's of course much better.
