### ISSUE TITLE
New E-Robot version

### ISSUE THREAD

**Issue by rugk** [rugk/erobot-language-de#3]
@bartatamas You released a new version of E-Robot (v 1.39).
So I assume there are new language strings. Can you please add them to the specific files?

**Comment by bartatamas** [comment]
How can I check changes between uploaded and current version? Is there a tool for that at github?

**Comment by rugk** [comment]
Well if you fork the repo you could replace all files with the original ones. Then you can create a pull request and it will show the changes.
However as I currently have already translated some strings these ones would also be shown as changes. So you would have to use the [original, English version](https://github.com/rugk/erobot-language-de/tree/v1.38.1-en) and compare it.

**Comment by bartatamas** [comment]
Hi, I have just commited changes.

**Comment by rugk** [comment]
Okay, thanks. So that's fixed now by https://github.com/rugk/erobot-language-de/commit/efa520685c194a3908e7697434105089c976b016.
